### ISSUE TITLE
I can´t use the plugin, please help me.

### ISSUE THREAD

**Issue by rawrlonely** [HENDRIX-ZT2/jpog-blender#4] opened 2022-01-15 10:41 UTC
I have downloaded the ZIP folder that contains the plugin, I have installed it following the instructions indicated in Blender 2.80, however when using "Toshi Model (.TMD)" that option simply does not appear, I do not understand if I have to install any anything else to get it working, I hope you can help me.
![Captura de pantalla (432)](https://user-images.githubusercontent.com/97786395/149618828-81698370-2f4b-415c-99ac-8248c40aebf2.png)

**Comment by HENDRIX-ZT2** [comment] 2022-03-07 15:42
Closed, duplicate of #3

**Closed as completed by HENDRIX-ZT2** 2022-03-07 15:42 UTC
